### ISSUE TITLE
Version number new release?

### ISSUE THREAD

**Issue by rwbc** [princesslana/princhess#332]
Hi Lana,

Did you revert some things, or is the new version number a typo?
(from 0.17.0 'back' to 0.15.2)

Guenther

**Comment by ianagbip1oti** [comment]
I had posted in the ccrl forum, https://kirill-kryukov.com/chess/discussion-board/viewtopic.php?p=142716#p142716

I added multipv to an older version so that it can be released/tested now. 0.17.0 is still the latest versoin.
