### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by SzotsGabor** [princesslana/princhess#35]
I have installed it under Arena and found odd behaviour:
1. Displayed memory allocation fluctuates wildly, from a couple of hundred to 2 GB (my Arena setting is 256 MB).
2. It uses more than 1 core, probably wants to use all cores of my 4-core machine.

This is under 64-bit Windows 10.

**Comment by ianagbip1oti** [comment]
> Displayed memory allocation fluctuates wildly, from a couple of hundred to 2 GB (my Arena setting is 256 MB).

How are you setting the area size? 

> It uses more than 1 core, probably wants to use all cores of my 4-core machine.

Hmm. This is unexpected. It should run 1 thread per core, but leaves it to the OS to spread them across cores.

**Comment by SzotsGabor** [comment]
Yes, Arena is a chess GUI and a common hash size for UCI engines can be set.

I have a 4-core machine and Process Explorer (an extended task manager) shows more than 50 % but that is changing and when I saw it I stopped the engine immediately so that my running tournaments will not be affected.

**Comment by ianagbip1oti** [comment]
Cool, It currently doesn't support setting the hash size, so just uses what it needs.

For core use, you also set the number of threads via the GUI? If so, for threading it's currently the same - it doesn't yet support setting the number of threads, and just uses the number of cpus.

Definitely plan to add these things. Since you've brought them up I'll probably work on them next.

**Comment by SzotsGabor** [comment]
Yes, there is a common setting for number of cores to use, and it is set to 1 in my case.

**Comment by ianagbip1oti** [comment]
I have added configuration of threads and hash size, and uploaded as version 0.3.0

**Comment by SzotsGabor** [comment]
Thank you. I will try it as soon as I have time.

**Comment by ianagbip1oti** [comment]
Awesome. The options and info it provides back to something like a gui is probably still in need of a bit of work, haha. So lmk if you spot anything else 👍

**Comment by SzotsGabor** [comment]
Hash size is in MB's, isn't it?
Anyway, before going to bed I played one game. Core usage is OK now, with setting 1 I get 25 % CPU usage. Memory allocation is still a bit odd, it starts at 130 MB and goes up to 735 MB but not higher.

**Comment by ianagbip1oti** [comment]
yeah, hash size is in mbs. It doesn't allocate the full hash and keep it around, so I would expect memory to fluctuate, But 735mb sounds does high and something I'll look at (assuming it was the 256 setting).

**Comment by SzotsGabor** [comment]
In fact it went up to 774 (settting was 256 under Arena).

It seems analysis mode is not implemented yet and in a game when it is its move it does not display anything (I always talk about Arena).

**Comment by ianagbip1oti** [comment]
I released 0.3.1 because it was doubling the size of the hash. Oops. It's still using a lot memory apart from the hash which will take some time to track down. I would expected to run about 500-550 now based on what you suggested before.

> Under what flag is it running?
Not sure what you mean by flag here

**Comment by SzotsGabor** [comment]
Your country. CCRL, of which I am a member, traditionally displays name and country of the author. BTW, are you the only author? I'm a bit confused about this princess Lana thing.

**Comment by ianagbip1oti** [comment]
Princess Lana is the name I tend to use online. It would be my preference for that to be the author name. https://github.com/zxqfl/sashimi/ was the original code base, but I haven't been able to get in touch with the author there. idk what the standard is as far as crediting previous code bases.

As for flag, well, idk. I'm an Australian living in California, haha. I guess go with USA flag, since it indicates the timezone I'm usually in.

As far as estimated strength, it's sitting in the 1800s on lichess right now https://lichess.org/@/princhess_bot

**Comment by SzotsGabor** [comment]
Thank you. Would you resent if we used your real name in our lists?

I think credit to the original author by name and/or a link is enough. But again, you are the Sashimi author, aren't you? Or do you refer to something before Sashimi?

**Comment by ianagbip1oti** [comment]
I'm not the Sashimi author. But all I know about them is their github. And it's definitely my plan to keep a link and record that it was where I started, just not sure if it's convention to keep them as an author or not.

If you want a real name, Lana Samson is fine.

**Comment by SzotsGabor** [comment]
I don't think you have to keep them as author after you have revealed everything about the origin.

And that solves my confusion about names so I'll submit Princess Lana as the author's name.

**Comment by ianagbip1oti** [comment]
> CCRL

I signed up for the forum there. Is it worth making a "New Engine" post, as I see there is for a few others?

**Comment by SzotsGabor** [comment]
> 
> 
> > CCRL
> 
> I signed up for the forum there. Is it worth making a "New Engine" post, as I see there is for a few others?

I don't think it is necessary as it has already been announced there in  another subforum (which only CCRL members have access to). Unless you want to say something you deem worth.

**Comment by ianagbip1oti** [comment]
Nope, nothing to add. Thanks!

**Comment by ianagbip1oti** [comment]
Closing as I believe everything here got addressed. Thanks for the testing in CCRL 👍
