### ISSUE TITLE
🐛 FIX: Princhess fails to start in cutechess in Windows 7

### ISSUE THREAD

**Issue by AlexBrunetti** [princesslana/princhess#88]
Hi,

I was never able to run the engine in cutechess-cli under Windows, it simply quits immediately.

Thanx,
Alex

**Comment by ianagbip1oti** [comment]
Oh damn, that sucks. I had thought the CCRL testing had been on windows (arena gui I believe). Not sure what cutechess would be doing differently. I'll see if I can get access to Windows somewhere to test sometime.

Which version are you running?

**Comment by ianagbip1oti** [comment]
<img width="979" alt="Screen Shot 2021-11-01 at 10 25 58 PM" src="https://user-images.githubusercontent.com/26780798/139791278-76d2f213-f743-435f-9460-47212d067431.png">

I just tried 0.5.0 quickly (it's late, so just a quick check). What is the cutechess command you are using to run? Perhaps there's something in there I haven't accounted for.

**Comment by AlexBrunetti** [comment]
Cutechess is this: https://github.com/cutechess/cutechess and works with 99% of engines.
I tested all Princhess versions and no one works with it.

Alex

**Comment by ianagbip1oti** [comment]
Yeah, I run all my tests with cutechess and also via openbench. I've never had issues, but my setups are all linux based.

**Comment by tissatussa** [comment]
i see this problem with CuteChess; i'm on Linux and all (pre-build assets of) Princhess versions work well in my CuteChess v1.2.0 -- the settings are basic, nothing special compared to other engines in CuteChess. Maybe you set 'XBoard' while 'UCI' is needed? I guess not, while UCI is default. I only have experience with Windows upto version 7 .. did you try to disable your virusscanner etc.? I have no other tips or explanations.

**Comment by ianagbip1oti** [comment]
<img width="978" alt="Screen Shot 2021-11-01 at 11 16 24 PM" src="https://user-images.githubusercontent.com/26780798/139795629-f0b33baa-8856-43a3-9dae-82b6f6d7abc1.png">

I have not been able to recreate an issue on the windows box I have access to. So, any more info there is to try and recreate this would be great.

**Comment by AlexBrunetti** [comment]
Well, in Windows 7 it just exit as I wrote:
![image](https://user-images.githubusercontent.com/62241591/139797393-c39c1ac9-35d0-4eee-9757-bfc15f7b1b63.png)
Now I tested it o a Windows 10 box and it works. Not a great issue then, I'll run there.

Thanx,
Alex

**Comment by ianagbip1oti** [comment]
That's really weird it works outside of cutechess, but not when run within it. I guess adding -debug doesn't give anymore info?

Glad you can at least run it on another box. And thanks for all the testing you do, it's appreciated.

**Comment by AlexBrunetti** [comment]
No, it quits immediately:

`H:\SUCE>cutechess-cli.exe -engine cmd=pr.exe -engine cmd=pr.exe -each tc=10+0.1 proto=uci -debug
21 >UciEngine(0): uci
22 >UciEngine(1): uci
Terminating process of engine UciEngine(0)
Terminating process of engine UciEngine(1)
Finished game 1 (UciEngine vs UciEngine): * {No result}
Score of UciEngine vs UciEngine: 0 - 0 - 0  [nan] 0
Elo difference: nan +/- nan, LOS: nan %, DrawRatio: nan %
Finished match`

Fortunately not many users still use Windows 7 :)

Alex

**Comment by eduherminio** [comment]
I'm afraid I'm having the same issue using Windows 10 and CuteChess 1.2.0.

CLI, all good:

```bash
$> princhess-0.5.0.exe
position startpos moves e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4 g8f6 d2d3 d7d6 e1g1 f8e7 c2c3 e8g8 b1d2 b7b5 a4b3
isready
readyok
go wtime 175976 btime 182000 winc 2000 binc 2000
info hashfull 1000
info depth 11 seldepth 16 nodes 8373 nps 24482 tbhits 0 score cp 15 time 342 pv c6a5 h2h3 h7h6 b3c2 c7c5 b2b4 c5c4 g1h2
bestmove c6a5
```

Cutechess, dies after the first go command (tested both w/ and without opening book):

![image](https://user-images.githubusercontent.com/11148519/141101931-1913812c-ce84-4dc2-841d-55201189203c.png)

**Comment by ianagbip1oti** [comment]
> I'm afraid I'm having the same issue using Windows 10 and CuteChess 1.2.0.

So this is slightly different to Brunetti's issue, in that it's not exiting immediately.

What options are set for the engines in the CuteChess run?

**Comment by eduherminio** [comment]
> > I'm afraid I'm having the same issue using Windows 10 and CuteChess 1.2.0.
> 
> So this is slightly different to Brunetti's issue, in that it's not exiting immediately.
> 
> What options are set for the engines in the CuteChess run?

Default ones.
If the logs don't lie:
```
<Princhess 0.5.0(1): id name Princhess 0.5.0
<Princhess 0.5.0(1): id author Princess Lana
<Princhess 0.5.0(1): option name Hash type spin min 1 max 65536 default 1
<Princhess 0.5.0(1): option name Threads type spin min 1 max 255 default 1
<Princhess 0.5.0(1): option name SyzygyPath type string
<Princhess 0.5.0(1): option name ExplorationConstant type spin min 1 max 65536 default 225
<Princhess 0.5.0(1): uciok
>Princhess 0.5.0(1): setoption name ExplorationConstant value 225
>Princhess 0.5.0(1): setoption name Hash value 1
>Princhess 0.5.0(1): setoption name SyzygyPath
>Princhess 0.5.0(1): setoption name Threads value 1
>Princhess 0.5.0(1): isready
<Princhess 0.5.0(1): readyok
```

**Comment by ianagbip1oti** [comment]
> > > I'm afraid I'm having the same issue using Windows 10 and CuteChess 1.2.0.
> > 
> > 
> > So this is slightly different to Brunetti's issue, in that it's not exiting immediately.
> > What options are set for the engines in the CuteChess run?
> 
> Default ones. If the logs don't lie:
> 
> ```
> <Princhess 0.5.0(1): id name Princhess 0.5.0
> <Princhess 0.5.0(1): id author Princess Lana
> <Princhess 0.5.0(1): option name Hash type spin min 1 max 65536 default 1
> <Princhess 0.5.0(1): option name Threads type spin min 1 max 255 default 1
> <Princhess 0.5.0(1): option name SyzygyPath type string
> <Princhess 0.5.0(1): option name ExplorationConstant type spin min 1 max 65536 default 225
> <Princhess 0.5.0(1): uciok
> >Princhess 0.5.0(1): setoption name ExplorationConstant value 225
> >Princhess 0.5.0(1): setoption name Hash value 1
> >Princhess 0.5.0(1): setoption name SyzygyPath
> >Princhess 0.5.0(1): setoption name Threads value 1
> >Princhess 0.5.0(1): isready
> <Princhess 0.5.0(1): readyok
> ```

Can you just try explicitly setting the Hash to something? Even like 16.

I have a typo in the default there (the default is 16, not 1). I'm wondering if cutechess actually sets it to 1, rather than just not setting it. Princhess probably hates a hash of 1.

**Comment by eduherminio** [comment]
Apologies for hijacking the issue @AlexBrunetti 🙏, I thought it could be the same issue.

**Comment by ianagbip1oti** [comment]
0.5.1 release done with a fix for that one https://github.com/princesslana/princhess/releases/tag/0.5.1

**Comment by AlexBrunetti** [comment]
> Can you in cmd after typing uci, also type go? And paste the screenshot here

In cmd it works fine. The problem is cutechess.

Alex

**Comment by ianagbip1oti** [comment]
Closing as old.
