### ISSUE TITLE
compilation gives version 0.0.0-dev ?

### ISSUE THREAD

**Issue by tissatussa** [princesslana/princhess#96]
i compiled your newest source code (by git clone) and then i did `cargo build --release` which gave me a proper Linux binary (without Nightly !) and the uci command shows `id name Princhess 0.0.0-dev` .. but i expect v0.5.1 !?

**Comment by ianagbip1oti** [comment]
This is intended. I use a version of 0.0.0-dev for any dev versions. The releases get version numbers compiled in when they'e built.
